---
- hosts: wsl
  name: ping
  connection: local
  tasks:
    - name: ping localhost machines
      ansible.builtin.ping:
    - name: echo varriable
      debug:
        msg: ssh_password - {{ ansible_user }} - {{ ansible_ssh_pass }}

#- hosts: windows_machines
#  name: ping
#  tasks:
#    - name: ping windows machines
#      ansible.builtin.ping:
#        data: crash
#
#- hosts: azure_machines
#  name: ping
#  tasks:
#    - name: ping azure machines
#      ansible.builtin.ping:
#        data: crash
#
#- hosts: linux_machines
#  name: ping
#  tasks:
#    - name: ping linux machines
#      ansible.builtin.ping:
#        data: crash
