---
- hosts: all
  name: Remove Setup
  connection: local
  tasks:
    - name: Remove packages
      become: true
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - fuse
        - zsh
        - ripgrep
        - luarocks
        - xclip
        - zip
        - fontconfig

    - name: Uninstall neovim and plugins
      command: "{{ item }}"
      loop:
        - "rm -rf {{ ansible_user_dir }}/.config/nvim"
        - "rm -rf {{ ansible_user_dir }}/.local/share/nvim"
        - "rm -rf {{ ansible_user_dir }}/.local/bin/nvim"

    - name: Remove Starship
      become: true
      file:
        path: "{{ ansible_user_dir }}/.config/starship.toml"
        state: absent

    - name: Remove Rust
      become: true
      file:
        path: "{{ ansible_user_dir }}/.cargo"
        state: absent

    - name: Remove Exa
      become: true
      file:
        path: "{{ ansible_user_dir }}/.cargo/bin/exa"
        state: absent

    - name: Remove Oh My Zsh
      become: true
      file:
        path: "{{ ansible_user_dir }}/.oh-my-zsh"
        state: absent

    - name: Remove fzf package
      command: "{{ item }}"
      loop:
        - "{{ ansible_user_dir }}/.fzf/uninstall"
        - "rm -rf {{ ansible_user_dir }}/.fzf"
      ignore_errors: yes

    - name: Remove Packer
      file:
        path: "{{ ansible_user_dir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
        state: absent
      become: true
      become_user: "{{ ansible_user }}"

    - name: Uninstall Docker
      apt:
        name: docker-ce
        state: absent
        autoremove: yes
      become: true
      when: ansible_pkg_mgr == 'apt'

    - name: Uninstall Docker
      yum:
        name: docker-ce
        state: absent
        autoremove: yes
      become: true
      when: ansible_pkg_mgr == 'yum'

    - name: Uninstall Helm
      file:
        path: /usr/local/bin/helm
        state: absent
      become: true

    - name: Uninstall K9s
      file:
        path: /usr/local/bin/k9s
        state: absent
      become: true

    - name: Uninstall KIND
      file:
        path: /usr/local/bin/kind
        state: absent
      become: true

