all:
  hosts:
  children:
    wsl:
      hosts:
        localhost:
          vars:
            ansible_connection: local
            ansible_python_interpreter: "{{ansible_playbook_python}}"

    # windows_machines:
    #   hosts:
    #     # replace your WINDOWS IP here
    #     172.25.213.187

    linux_machines:

    azure_machines:

