all:
  hosts:
  children:
    wsl:
      hosts:
        localhost:
          vars:
            ansible_connection: local
            ansible_python_interpreter: "{{ansible_playbook_python}}"

    windows_machines:
      hosts:
        172.26.192.1

    linux_machines:

    azure_machines:

