---
- name: Uninstall Docker
  apt:
    name: docker-ce
    state: absent
    autoremove: yes
  when: ansible_pkg_mgr == 'apt'

- name: Uninstall Docker
  yum:
    name: docker-ce
    state: absent
    autoremove: yes
  when: ansible_pkg_mgr == 'yum'

- name: Verify Docker is uninstalled
  shell: docker --version
  register: docker_version
  ignore_errors: yes

- name: Install packages to allow apt to use repository over HTTPS
  apt:
    name:
      - ca-certificates
      - gnupg
      - apt-transport-https
    state: present
    update_cache: yes

- name: Add docker's offical GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get Ubuntu release version
  shell: lsb_release -cs
  register: ubuntu_version

- name: Get architecture
  shell: dpkg --print-architecture
  register: architecture

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
    state: present
    filename: docker

- name: Update apt packages
  apt:
    update_cache: "yes"
    force_apt_get: "yes"

- name: Install Docker engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

