---
vault:
  user:
    name: tnh5hc
    password: RBVHWinter22!
    ssh_password: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
      NhAAAAAwEAAQAAAYEAsugjsa8ey5LJelrvJDsIQL/IWcUa1rB4HrlW+LSUPhv92gfIp8M8
      5w4BkyMjUEn1RT+IDRnk9WoLkvDUyur1d1FLC5XHB4B4nFkl5OEoqvW0Xw3bRqY8rp7I0R
      FWUSANEi0x76CHeWiUvwmTbym7Gc4wxJRqV4a6KahAzn73G/CJxxAgmiJtAkashe6+qLSV
      yBmc8zBFrDMnIDz0kiA/jwmlNZjrkyTUDUkzOe9NZo0x/lgCeUkRWDOqcaM8yUvFpY8utQ
      zKOy4bh9lvQHLJ/eyTvII312fNpmDXqCilGJJbk8hknc3JdasaeLNDzmVePbDVBoYlNXpD
      3ituCku6CNy1J1gceeb8qwb2UoSZvDOVFcSX2yb5GlGav8ZzLrx9Y/Hy2zS37jzVi6ypre
      zVmD0yfuv8AoTydGUKduHYKla7yDS3K0JFdxxHylnW+4GB+lsKnmwLakhOBn0+dfwmUq2m
      iKXIHjOybBnlP7rGQtc1OWrmbd4OAd2ADuutgI2TAAAFiMVxLozFcS6MAAAAB3NzaC1yc2
      EAAAGBALLoI7GvHsuSyXpa7yQ7CEC/yFnFGtaweB65Vvi0lD4b/doHyKfDPOcOAZMjI1BJ
      9UU/iA0Z5PVqC5Lw1Mrq9XdRSwuVxweAeJxZJeThKKr1tF8N20amPK6eyNERVlEgDRItMe
      +gh3lolL8Jk28puxnOMMSUaleGuimoQM5+9xvwiccQIJoibQJGrIXuvqi0lcgZnPMwRawz
      JyA89JIgP48JpTWY65Mk1A1JMznvTWaNMf5YAnlJEVgzqnGjPMlLxaWPLrUMyjsuG4fZb0
      Byyf3sk7yCN9dnzaZg16gopRiSW5PIZJ3NyXWrGnizQ85lXj2w1QaGJTV6Q94rbgpLugjc
      tSdYHHnm/KsG9lKEmbwzlRXEl9sm+RpRmr/Gcy68fWPx8ts0t+481Yusqa3s1Zg9Mn7r/A
      KE8nRlCnbh2CpWu8g0tytCRXccR8pZ1vuBgfpbCp5sC2pITgZ9PnX8JlKtpoilyB4zsmwZ
      5T+6xkLXNTlq5m3eDgHdgA7rrYCNkwAAAAMBAAEAAAGBAKCaY/COFEcLbnK4TxVnKPF3OJ
      PdrUotAKgUGU8KTEm1Nx0S/74aNgH1QNSlJn5c5iFT9v5L0I2+tMUkDOJcKh8CiyvLOPAz
      FBLGtI3S0n8mMtVhywaRFMhtIjkMJ0CMVS+MAtfqc7M5fs4/+mpAPAXeY0kVMqGAAH6E3C
      iDMbGTLRvWDm5PmSwB5b4VpHIuKoeG9q4ZF3KOOQFntuW2rVfqgLSsok1lMjb7D1Fi0UjO
      V6LLvuzB+yACwW9h6p+JtFMDh0DRobd3+6GdoDVsDcxTd+B4B5bWY3rnJX9Sa0alYFdFFY
      SG2md99jcQjX/kkOUJDCFA8wNI+2puiLtvnZMY5HMIAkcP/zRkjM/pkUf9QvLrf0Hw1Tjz
      lDvGA78mlmciyJ7blrGjEqRp/J1noEm8kVz+582vJwHOfxvZGkWc4fKG5z5QGX+vw4AnLu
      vywD8nIRvF0+EiJffBimgcjbZoaSXMUrkioDFkABgh0KpXuSsDR5LLXOBJ3wzZb37KgQAA
      AMEA4bnrBRSzbtPe99ujvh1T5tWKPbmA9NcMJ8m8eeN/cemGRdPLxs0wXuE217WodMyosO
      MYouzGsfjVvP1ITi7b26qDN0HODfGn6yLHhI7OyjUQ8itGNzr2VQ20Z2VxLszTzrxBFmUY
      4f+c3sjQ2MuezN4gR6cwwqR1+JhjzceL/hZMNqnXMQoc4oNBwl0qH3e9Yrx7XYW9oI8VGR
      7QJnzq1DQNHIWtAnvywF9doUubjx1iANETsSRuNjBzOo0h2L1QAAAAwQDjo8HpgsF5Bvr/
      fr7pTsUgo41IPsughreTs4HXy8zc17B6xwKMn1EnM3LWLQaeP4zulHKPpg4i//dwu4GQZX
      S1BjfPlJ8vmujYmAKz1poB5/gyO4PFt/c9jrz1YRruHz3psbGu3Km+YHP4KhxlIY7+q7jh
      KdawO2mlHv5WZ5+e8AXMF8wEXsESxiKI2FnwLC5248HwFVYppq7EZWJRowrOTXQAjniEnL
      bwqULVRr1u8IjbPgfuz4VIjR4V0mX2W/0AAADBAMkyHcFV8ilKV6GoB+lc9Kz2S8fPZb6U
      ziXYtTzMnIcgfrGGBuPfl8hooF9PSZQvfdww/NdQgtQdJmYnOYEallsM5rLYNrKUvEm/xw
      rYL0XS+uCwDqoTfiokfRaoLxVVg15ujeO1vhBrOhFmstkaGQ+pKviu+pagMX/hcIveT4Z/
      HYPoLBYlw2aX/noP3pIvDPpq9a3SOAq3uyIsdWhWpTdqtlVzu1ncxclCVFEaQOPgq6jlJb
      FzR0xThME5mZaczwAAAA50bmg1aGNATmhhdC1QQwECAw==
      -----END OPENSSH PRIVATE KEY-----
